const NAVER_CLIENT_ID = process.env.NEXT_PUBLIC_NAVER_CLIENT_ID;
const NAVER_REDIRECT_URI = process.env.NEXT_PUBLIC_NAVER_REDIRECT_URI;
const STATE = 'false';

const KAKAO_API_KEY = process.env.NEXT_PUBLIC_KAKAO_REST_API_KEY;
const KAKAO_REDIRECT_URI = process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI;

export {
  NAVER_CLIENT_ID,
  NAVER_REDIRECT_URI,
  STATE,
  KAKAO_API_KEY,
  KAKAO_REDIRECT_URI,
};
